# Generated by Django 5.1.2 on 2025-01-09 16:59

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tags_options_tags_title_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='title',
        ),
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default='Default Tag', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='tid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnop1234567890', length=10, max_length=20, prefix='tag', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.tags'),
        ),
    ]
