# Generated by Django 5.1.2 on 2025-01-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default='+123', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
