# Generated by Django 5.1.2 on 2025-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendor_contact_alter_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='something street 123', max_length=100),
        ),
    ]
