# Generated by Django 5.1.2 on 2025-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default='3'),
        ),
    ]
